version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - laravel

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_worker
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    entrypoint: ["php", "artisan", "queue:work", "--tries=3"]
    depends_on:
      - db
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: